sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install -e ".[dev]"
script: py.test --cov-report=xml --cov-report=html --cov-report term-missing --cov=ec2_ssh/ec2_helpers
after_success:
  - coveralls
